spring:
  aop:
    auto: true
    proxy-target-class: true
  jackson:
    #    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    dynamic:
      primary: test_db #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        test_db:
          url: jdbc:mysql://localhost:3306/test_db?useSSL=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123
          driver-class-name: com.mysql.cj.jdbc.Driver
          initialSize: 5
          minIdle: 5
          maxActive: 50
          connection-test-query: SELECT 1 FROM DUAL
logging:
  level:
    com.baomidou.mybatisplus.samples.pagination: debug
    com.baomidou.dynamic: debug
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

